const tintColor = '#2f95dc';

export const colors = {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  gray: '#888888',
  background1: '#B721FF',
  background2: '#21D4FD',

  black: "#2c2c2c",
  clearBlue: "#2a7ff6",
  warmGrey: "#777777",
  disabled: "#777777",
  lightGrey: "#d8d8d8",
  paleGrey: "#f7f8f9",
  white: "#ffffff",
  whiteTwo: "#f5f5f5",
  tomato: "#ed4847",
  greyish: "#aaaaaa",
  greyishTwo: "#a8a8a8",
  lightPeriwinkle: "#bfc6f6",
  blue: '#2A7FF6',
  goldenYellow: '#ffc61b',
}
