require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Add a require_relative for this package's script:
require_relative '../node_modules/react-native-permissions/scripts/setup'



# platform :ios, min_ios_version_supported
platform :ios, '13' # min_ios_version_supported
prepare_react_native_project!

# ⬇️ uncomment the permissions you need
setup_permissions([
   'AppTrackingTransparency',
  # 'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
   'Camera',
   'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
   'Microphone',
  # 'Motion',
   'Notifications',
   'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])



# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
production = ENV["PRODUCTION"] == "1"
$RNFirebaseAnalyticsWithoutAdIdSupport=true

ENVFILES = {
    'Debug' => '$(PODS_ROOT)/../../.env',
    'Staging' => '$(PODS_ROOT)/../../.env.staging',
    'Release' => '$(PODS_ROOT)/../../.env.production',
  }

  

  def rokebiPods
    config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

    pod 'KakaoSDKCommon' , '~> 2.11.1' # 필수 요소를 담은 공통 모듈
    pod 'KakaoSDKAuth', '~> 2.11.1' # 사용자 인증
    pod 'KakaoSDKUser', '~> 2.11.1' # 카카오 로그인, 사용자 관리
    pod 'KakaoSDKTalk', '~> 2.11.1' # 친구, 메시지(카카오톡)
    pod 'KakaoSDKShare', '~> 2.11.1' # 메시지(카카오톡 공유 2.11.0 미만 버전)
    # pod 'KakaoSDKShare'  # 메시지(카카오톡 공유 2.11.0 이상 버전)
    pod 'KakaoSDKTemplate', '~> 2.11.1' # 메시지 템플릿 

  flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

  use_react_native!(
    :path => config[:reactNativePath],

        # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
 
  # pod 'AppCenter/Core', '4.3.0'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit', '~> 14.0.0'
  # pod 'FBSDKShareKit'

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase/Analytics', :modular_headers => true
  pod 'Firebase/DynamicLinks', :modular_headers => true

  # use_flipper!({ "Flipper-DoubleConversion" => "3.2.0.1"})
  # use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3'})`

end

target 'RokebiGlobal' do
  rokebiPods
 
end

target 'RokebiESIM' do
  rokebiPods
  pod 'react-native-sim-cards-manager', :path => '../node_modules/react-native-sim-cards-manager'

  # pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/latest/xcframework.podspec'

  pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/12.0.0/xcframework.podspec'
  pod 'RNChannelIO', :path => '../node_modules/react-native-channel-plugin'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'NTrackerSDKExt'
   

end
 
# post_install do |installer|
#   react_native_post_install(
#     installer,
#     # Set `mac_catalyst_enabled` to `true` in order to apply patches
#     # necessary for Mac Catalyst builds
#     :mac_catalyst_enabled => false
#   )
#   __apply_Xcode_12_5_M1_post_install_workaround(installer)
# end
post_install do |installer|
  flipper_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
      if target.name == 'react-native-config'
        # puts target.name 타겟네임 보는 법
        config.build_settings['ENVFILE'] = ENVFILES[config.name]
        # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        # config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
      end
    end
  end

end 
