require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

ENVFILES = {
    'Debug' => '$(PODS_ROOT)/../../.env',
    'Staging' => '$(PODS_ROOT)/../../.env.staging',
    'Release' => '$(PODS_ROOT)/../../.env.production',
  }

  

  def rokebiPods
    config = use_native_modules!

    use_react_native!(:path => config[:reactNativePath], 
    :hermes_enabled => false
  )

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  # pod 'AppCenter/Core', '4.3.0'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit', '~> 14.0.0'
  # pod 'FBSDKShareKit'

  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'

  #  pod 'Adjust', '~> 4.29.2'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!()
  use_flipper!("Flipper" => "0.93.0", "Flipper-DoubleConversion" => "1.1.7")

  end

target 'RokebiGlobal' do
  rokebiPods

  post_install do |installer|
    flipper_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
          # config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          # config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
        end
      end
    end
  
  end  
end

target 'RokebiESIM' do
  rokebiPods
  pod 'react-native-sim-cards-manager', :path => '../node_modules/react-native-sim-cards-manager'

end

target 'RokebiUSIM' do
  rokebiPods
end
